In [1]:
import pandas as pd

In [2]:
data={
    'Name':['Neha','Satya','Deepthi'],
    'Age':[12,18,19],
    'Houses':['Red','White','Yellow']
}
df=pd.DataFrame(data)
df

      Name  Age  Houses
0     Neha   12     Red
1    Satya   18   White
2  Deepthi   19  Yellow

In [3]:
df.shape

(3, 3)

In [4]:
df.size

9

In [5]:
df.ndim

2

In [6]:
df.dtypes

Name      object
Age        int64
Houses    object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Houses  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [8]:
df.memory_usage()

Index     132
Name       24
Age        24
Houses     24
dtype: int64

In [9]:
df.describe()

             Age
count   3.000000
mean   16.333333
std     3.785939
min    12.000000
25%    15.000000
50%    18.000000
75%    18.500000
max    19.000000

In [10]:
df['Age']

0    12
1    18
2    19
Name: Age, dtype: int64

In [12]:
df['Name']

0       Neha
1      Satya
2    Deepthi
Name: Name, dtype: object

In [15]:
df.drop('Age',axis=1)

      Name  Houses
0     Neha     Red
1    Satya   White
2  Deepthi  Yellow

In [25]:
df.rename(columns={'Houses':'Home'},inplace=True)
print(df)

      Name  Age    Home
0     Neha   12     Red
1    Satya   18   White
2  Deepthi   19  Yellow

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Houses  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [26]:
data={
    'Name':['Neha','Satya','Deepthi'],
    'Age':[12,18,19],
    'Houses':['Red','White','Yellow'],
    'Subject':['science','maths','physics']
}
df=pd.DataFrame(data)
df

      Name  Age  Houses  Subject
0     Neha   12     Red  science
1    Satya   18   White    maths
2  Deepthi   19  Yellow  physics

In [28]:
df.drop('Subject',axis=1)

      Name  Age  Houses
0     Neha   12     Red
1    Satya   18   White
2  Deepthi   19  Yellow

In [29]:
df.isnull()

    Name    Age  Houses  Subject
0  False  False   False    False
1  False  False   False    False
2  False  False   False    False

In [30]:
df.dropna()

      Name  Age  Houses  Subject
0     Neha   12     Red  science
1    Satya   18   White    maths
2  Deepthi   19  Yellow  physics

In [32]:
df.shape

(3, 4)

In [33]:
df.describe()

             Age
count   3.000000
mean   16.333333
std     3.785939
min    12.000000
25%    15.000000
50%    18.000000
75%    18.500000
max    19.000000

In [34]:
df.memory_usage()

Index      132
Name        24
Age         24
Houses      24
Subject     24
dtype: int64

In [35]:
df.size

12